### PR TITLE
Added setup.py and re-organized contents

### PR DESCRIPTION
**Pull request by markgschwind**
Was looking to use the image viewer for a personal project. For learning purposes, I created a setup.py file with the original author's information and reorganized the files into a package that can be install with the following pip command. 

`pip install git+https://github.com/markgschwind/PyQtImageViewer`

Please take a look if this is something you'd like to incorporate into your repository.

### CODE REVIEW

**Comment by marcel-goldschen-ohm** [comment]
Wow, thanks Mark! This is awesome. Do you mind also editing the Install section of the README to add the option for pip installing? Then I'll merge after that.

Cheers,
Marcel

**Comment by marcel-goldschen-ohm** [comment]
I'm getting an error when attempting to pip install (any ideas?):

(test) vector-insert-mutations % pip install git+https://github.com/marcel-goldschen-ohm/PyQtImageViewer
Collecting git+https://github.com/marcel-goldschen-ohm/PyQtImageViewer
  Cloning https://github.com/marcel-goldschen-ohm/PyQtImageViewer to /private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-req-build-j3u1iw32
  Running command git clone --filter=blob:none --quiet https://github.com/marcel-goldschen-ohm/PyQtImageViewer /private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-req-build-j3u1iw32
  Resolved https://github.com/marcel-goldschen-ohm/PyQtImageViewer to commit 58f18f297f08f5889aa6586bdf911d39b7fc5628
  Preparing metadata (setup.py) ... done
Collecting PyQt5
  Downloading PyQt5-5.15.9.tar.gz (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 5.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/opt/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-build-env-ywr27uxb/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-build-env-ywr27uxb/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-build-env-ywr27uxb/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-install-53ch4_14/pyqt5_bd770b19f15f4e2faa4cbe89a4df7c3a/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-build-env-ywr27uxb/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-build-env-ywr27uxb/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/cq/0x3wj8sx1_dbbm61zp0zqbmm0000gn/T/pip-build-env-ywr27uxb/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by markgschwind** [comment]
Hmm. I was able to install from your git repo with my current env. Let me check it it works on a fresh env without PyQt5, numpy, and pillow packages pre-installed. 

Python Version: v3.11.3 Windows 64-bit.

## Test1 with fresh python venv and base pip package (22.3.1)
```
D:\testenv>D:\testenv\test\Scripts\activate

(test) D:\testenv>pip install git+https://github.com/marcel-goldschen-ohm/PyQtImageViewer
Collecting git+https://github.com/marcel-goldschen-ohm/PyQtImageViewer
  Cloning https://github.com/marcel-goldschen-ohm/PyQtImageViewer to c:\users\mlgsc\appdata\local\temp\pip-req-build-6w8mard0
  Running command git clone --filter=blob:none --quiet https://github.com/marcel-goldschen-ohm/PyQtImageViewer 'C:\Users\MLGsc\AppData\Local\Temp\pip-req-build-6w8mard0'
  Resolved https://github.com/marcel-goldschen-ohm/PyQtImageViewer to commit 58f18f297f08f5889aa6586bdf911d39b7fc5628
  Preparing metadata (setup.py) ... done
Collecting PyQt5
  Using cached PyQt5-5.15.9-cp37-abi3-win_amd64.whl (6.8 MB)
Collecting numpy
  Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)
Collecting Pillow
  Using cached Pillow-9.5.0-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting PyQt5-sip<13,>=12.11
  Using cached PyQt5_sip-12.12.1-cp311-cp311-win_amd64.whl (78 kB)
Collecting PyQt5-Qt5>=5.15.2
  Using cached PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
Installing collected packages: PyQt5-Qt5, PyQt5-sip, Pillow, numpy, PyQt5, PyQtImageViewer
  DEPRECATION: PyQtImageViewer is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for PyQtImageViewer ... done
Successfully installed Pillow-9.5.0 PyQt5-5.15.9 PyQt5-Qt5-5.15.2 PyQt5-sip-12.12.1 PyQtImageViewer-2.0.0.post1 numpy-1.24.3

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(test) D:\testenv>
```

## Ran Test2 updating my pip package (23.1.2) before installing
```
D:\>mkdir testenv2

D:\>cd testenv2

D:\testenv2>D:\Py3113\python.exe -m venv test2

D:\testenv2>D:\testenv2\test2\Scripts\activate

(test2) D:\testenv2>pip install --upgrade pip
Requirement already satisfied: pip in d:\testenv2\test2\lib\site-packages (22.3.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
ERROR: To modify pip, please run the following command:
D:\testenv2\test2\Scripts\python.exe -m pip install --upgrade pip

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

(test2) D:\testenv2>D:\testenv2\test2\Scripts\python.exe -m pip install --upgrade pip
Requirement already satisfied: pip in d:\testenv2\test2\lib\site-packages (22.3.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.1.2

(test2) D:\testenv2>pip install git+https://github.com/marcel-goldschen-ohm/PyQtImageViewer
Collecting git+https://github.com/marcel-goldschen-ohm/PyQtImageViewer
  Cloning https://github.com/marcel-goldschen-ohm/PyQtImageViewer to c:\users\mlgsc\appdata\local\temp\pip-req-build-1j9ny9qe
  Running command git clone --filter=blob:none --quiet https://github.com/marcel-goldschen-ohm/PyQtImageViewer 'C:\Users\MLGsc\AppData\Local\Temp\pip-req-build-1j9ny9qe'
  Resolved https://github.com/marcel-goldschen-ohm/PyQtImageViewer to commit 58f18f297f08f5889aa6586bdf911d39b7fc5628
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyQt5 (from PyQtImageViewer==2.0.0.post1)
  Using cached PyQt5-5.15.9-cp37-abi3-win_amd64.whl (6.8 MB)
Collecting numpy (from PyQtImageViewer==2.0.0.post1)
  Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)
Collecting Pillow (from PyQtImageViewer==2.0.0.post1)
  Using cached Pillow-9.5.0-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting PyQt5-sip<13,>=12.11 (from PyQt5->PyQtImageViewer==2.0.0.post1)
  Using cached PyQt5_sip-12.12.1-cp311-cp311-win_amd64.whl (78 kB)
Collecting PyQt5-Qt5>=5.15.2 (from PyQt5->PyQtImageViewer==2.0.0.post1)
  Using cached PyQt5_Qt5-5.15.2-py3-none-win_amd64.whl (50.1 MB)
Building wheels for collected packages: PyQtImageViewer
  Building wheel for PyQtImageViewer (pyproject.toml) ... done
  Created wheel for PyQtImageViewer: filename=PyQtImageViewer-2.0.0.post1-py3-none-any.whl size=14066 sha256=d72751d7035f5d49b620670eb610332450fb06396988e7ed9445db947212d921
  Stored in directory: C:\Users\MLGsc\AppData\Local\Temp\pip-ephem-wheel-cache-n_23tju5\wheels\6f\4d\eb\8154ac163ceaca20926db0583546d98be0a54d41dc46059552
Successfully built PyQtImageViewer
Installing collected packages: PyQt5-Qt5, PyQt5-sip, Pillow, numpy, PyQt5, PyQtImageViewer
Successfully installed Pillow-9.5.0 PyQt5-5.15.9 PyQt5-Qt5-5.15.2 PyQt5-sip-12.12.1 PyQtImageViewer-2.0.0.post1 numpy-1.24.3

(test2) D:\testenv2>
```

**Comment by markgschwind** [comment]
Give me a few and I can try on a conda env as well as on my mac.

**Comment by marcel-goldschen-ohm** [comment]
Sounds good.

**Comment by markgschwind** [comment]
Update:

Was able to try the following test cases

- Windows Conda Env: Working
- macOS Conda Env: Failed

It looks like the process fails when trying to install PyQt5. 

> Downloading PyQt5-5.15.9.tar.gz (3.2 MB)
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 5.6 MB/s eta 0:00:00
> Installing build dependencies ... done
> Getting requirements to build wheel ... done
> Preparing metadata (pyproject.toml) ... error
> error: subprocess-exited-with-error

I tried installing pyqt to the conda env `conda install pyqt` and then installing via git but it looks like the process freezes instead of fails, still on the pyqt piece.

```
(base) markgschwind@Marks-Air ~ % conda activate testpipenv
(testpipenv) markgschwind@Marks-Air ~ % pip install git+https://github.com/marcel-goldschen-ohm/PyQtImageViewer
Collecting git+https://github.com/marcel-goldschen-ohm/PyQtImageViewer
  Cloning https://github.com/marcel-goldschen-ohm/PyQtImageViewer to /private/var/folders/xv/yp0pp13s0r98lwtct0k75jjw0000gn/T/pip-req-build-uvvlb0lx
  Running command git clone --filter=blob:none --quiet https://github.com/marcel-goldschen-ohm/PyQtImageViewer /private/var/folders/xv/yp0pp13s0r98lwtct0k75jjw0000gn/T/pip-req-build-uvvlb0lx
  Resolved https://github.com/marcel-goldschen-ohm/PyQtImageViewer to commit 58f18f297f08f5889aa6586bdf911d39b7fc5628
  Preparing metadata (setup.py) ... done
Collecting PyQt5 (from PyQtImageViewer==2.0.0.post1)
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... -
```

**Comment by marcel-goldschen-ohm** [comment]
Nice job narrowing down the error (yup, I'm on a Mac). Would be great if it's an easy fix ;)

**Comment by markgschwind** [comment]
Not sure why those popped up here  ^. 

I'm by no means a python expert, but the PyQt5 dependency is removed, you are able to install to macOS. This might be the best approach anyways as your package works for both PyQt5 and PyQt6 (didn't think about this when I wrote the original setup dependencies).

**Comment by marcel-goldschen-ohm** [comment]
Yeah, sounds good as it seems like the MacOS M1-2 chip ARM architecture is only supported by PyQt6 at the moment. It is weird though as I have an M1 mac and I have an older environment with PyQt5 installed and working fine, I wish I recalled how I did that 😉

**Pull request merged**
